paths:
    cache: files/bolt/app/cache
    config: files/bolt/app/config
    database: files/bolt/app/database
    web: %site%/files/bolt/public
    themebase: files/bolt/public/theme
    files: files/bolt/public/files
    view: files/bolt/public/bolt-public/view
