paths:
    cache: app/cache
    config: app/config
    database: app/database
    web: %site%/vhosts/hrsvrt.ca/permashutters.hrsvrt.ca/bolt
    themebase: public/theme
    files: public/files
    view: public/bolt-public/view
