paths:
    cache: bolt/app/cache
    config: bolt/app/config
    database: app/database
    web: bolt/public
    themebase: bolt/public/theme
    files: bolt/public/files
    view: bolt/public/bolt-public/view
