paths:
    cache: app/cache
    config: app/config
    database: app/database
    web: bolt/public
    themebase: public/theme
    files: public/files
    view: public/bolt-public/view
paths:
    web: "%site$/bolt/bolt
"
